apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest-jdk21
    resources:
      requests:
        memory: "8Gi"
        cpu: "4"
      limits:
        memory: "8Gi"
        cpu: "4"
    securityContext:
      runAsUser: 0

  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    resources:
      requests:
        memory: "8Gi"
        cpu: "4"
      limits:
        memory: "8Gi"
        cpu: "4"
    tty: true
    command:
    - sleep
    args:
    - 1d
    volumeMounts:
    - mountPath: /kaniko/.docker
      name: docker-config

  - name: dind
    image: docker:20.10.13-dind
    resources:
      requests:
        memory: "8Gi"
        cpu: "4"
      limits:
        memory: "8Gi"
        cpu: "4"
    tty: true
    command:
    - cat
    volumeMounts:
    - mountPath: /root/.docker
      name: docker-config
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375

  - name: docker-daemon
    image: docker:20.10.13-dind
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""

  volumes:
  - name: docker-config
    emptyDir: {}
