name: Build precompiled DOCA for latest Kernels

on:
  schedule:
  - cron: 0 9 * * mon-fri
  push:
    branches:  # TODO: remove after testing
    - feature/precompiled-ofed-per-kernel

env:
  # TODO: ask ivan (maybe also alex) about what automation to maybe add for promotion from nvstaging to NGC
  # OFED releases: ask vlad.l who knows about it - perhaps mohamed.(!t)
  NVCR_DOCKER_REGISTRY: nvcr.io/nvstaging/mellanox  # TODO: verify if to publish to NGC or directly to nvstaging
  DOCKER_IMAGE_NAME: doca-driver

jobs:
  fetch_latest_doca_version:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch latest DOCA version
      id: fetch_latest_doca_version
      run: |
        echo latest_doca_version=$(
          curl -fsSL 'https://linux.mellanox.com/public/repo/mlnx_ofed/?C=M;O=D' | grep -Eo 'href="([0-9\.-]+)/"' | head -n 1 | grep -Eo '[0-9\.-]+'
        ) | tee -a $GITHUB_OUTPUT  # examples: 23.10-0.5.5.0 or 24.07-0.6.1.0
    outputs:
      latest_doca_version: ${{ steps.fetch_latest_doca_version.outputs.latest_doca_version }}

  precompile_and_publish_doca_for_ubuntu:
    needs:
    - fetch_latest_doca_version
    runs-on: ubuntu-latest
    env:
      LATEST_DOCA_VERSION: ${{ needs.fetch_latest_doca_version.outputs.latest_doca_version }}
    strategy:
      matrix:
        flavor:
        - generic
        - aws
        - azure
        - oracle
        - nvidia
        version:
        - '24.04'
        - '22.04'
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.NVCR_DOCKER_REGISTRY }}
        username: ${{ secrets.NVCR_USERNAME }}
        password: ${{ secrets.NVCR_TOKEN }}
    - name: Fetch latest Kernel version
      run: |
        echo LATEST_KERNEL_VERSION=$(docker run --rm ubuntu:${{ matrix.version }} bash -c "
          apt-get update > /dev/null
          apt-cache search --names-only linux-image | grep -Eo 'linux-image-[0-9.-]+${{ matrix.flavor }}' | sed -E 's/linux-image-//g' | sort -V | tail -n 1"
        ) | tee -a $GITHUB_ENV
    - name: Define docker tag
      run: |
        echo DOCKER_TAG=$LATEST_DOCA_VERSION-$LATEST_KERNEL_VERSION-ubuntu${{ matrix.version }} | tee -a $GITHUB_ENV  # example: 24.07-0.6.1.0-6.8.0-46-generic-ubuntu24.04
    - name: Check if published precompiled DOCA for kernel version
      id: check-if-published-precompiled-for-kernel
      run: |
        if skopeo list-tags docker://$NVCR_DOCKER_REGISTRY/$DOCKER_IMAGE_NAME | jq '.Tags[]' -r | grep $LATEST_DOCA_VERSION | grep ${{ matrix.flavor }}-ubuntu${{ matrix.version }}
        then
          echo NEW_BUILD_REQUIRED=false >> $GITHUB_ENV
        else
          echo NEW_BUILD_REQUIRED=true  >> $GITHUB_ENV
        fi
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/setup-qemu-action@v3
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/setup-buildx-action@v3
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64,linux/arm64
        file: Ubuntu_Dockerfile
        build-args: |
          D_OS=ubuntu${{ matrix.version }}
          D_OFED_VERSION=${{ env.LATEST_DOCA_VERSION }}
          D_KERNEL_VER=${{ env.LATEST_KERNEL_VERSION }}
          D_BASE_IMAGE=ubuntu:${{ matrix.version }}
        tags: ${{ env.NVCR_DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
        push: false  # TODO: change to true once build successful and satisfied with the matrix

  precompile_and_publish_doca_for_redhat_and_coreos:
    # if: false
    needs:
    - fetch_latest_doca_version
    runs-on: ubuntu-latest
    env:
      LATEST_DOCA_VERSION: ${{ needs.fetch_latest_doca_version.outputs.latest_doca_version }}
      RH_USERNAME: mzeevi@nvidia.com  # TODO: check for an existing service account (or create one)
    strategy:
      matrix:
        os:
        - rhel
        version:
        - '9.4'
        - '9.3'
        - '9.2'
        - '8.10'
        - '8.9'
        - '8.8'
        include:
        - os: rhcos
          version: '4.16'
          rh_major_version_to_use_for_latest_kernel_lookups: '9'
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: registry.redhat.io  # required for build
        username: ${{ env.RH_USERNAME }}
        password: ${{ secrets.RH_PASSWORD }}  # TODO: add secret in github
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.NVCR_DOCKER_REGISTRY }}
        username: ${{ secrets.NVCR_USERNAME }}  # TODO: add secret in github
        password: ${{ secrets.NVCR_TOKEN }}     # TODO: add secret in github
    - name: Fetch latest Kernel version
      run: |
        if [[ "${{ matrix.os }}" == "rhel" ]]
        then
          major_version=$(echo ${{ matrix.version }} | cut -d . -f 1)
        elif [[ "${{ matrix.os }}" == "rhcos" ]]
        then
          major_version=${{ matrix.rh_major_version_to_use_for_latest_kernel_lookups }}
        fi
        echo LATEST_KERNEL_VERSION=$(docker run --rm redhat/ubi$major_version:latest yum repoquery | grep kernel-headers | cut -d ':' -f 2) | tee $GITHUB_ENV
    - name: Define docker tag
      run: |
        echo DOCKER_TAG=$LATEST_DOCA_VERSION-$LATEST_KERNEL_VERSION-${{ matrix.os }}${{ matrix.version }} >> $GITHUB_ENV  # example: 24.07-0.6.1.0-5.14.0-427.37.1.el9_4.x86_64-rhel9.4
    - name: Check if published precompiled DOCA for kernel version
      id: check-if-published-precompiled-for-kernel
      run: |
        if skopeo list-tags docker://$NVCR_DOCKER_REGISTRY/$DOCKER_IMAGE_NAME | jq '.Tags[]' -r | grep $LATEST_DOCA_VERSION | grep ${{ matrix.os }}${{ matrix.version }}
        then
          echo NEW_BUILD_REQUIRED=false >> $GITHUB_ENV
        else
          echo NEW_BUILD_REQUIRED=true  >> $GITHUB_ENV
        fi
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/setup-qemu-action@v3
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/setup-buildx-action@v3
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      name: Determine base image
      run: |
        if [[ "${{ matrix.os }}" == "rhel" ]]
        then
          echo BASE_IMAGE=$(TBD) | tee -a $GITHUB_ENV  # TODO: find dynamic command to lookup image
        elif [[ "${{ matrix.os }}" == "rhcos" ]]
        then
          # podman login registry.redhat.io --username=${RH_USERNAME} --password=${RH_PASSWORD}  # TODO: see if required
          echo BASE_IMAGE=$(oc adm release info ${{ matrix.version }}.0 --image-for=driver-toolkit) | tee -a $GITHUB_ENV
        fi
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/build-push-action@v4
      with:
        platforms: ${{ matrix.os == 'rhel' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
        file: RHEL_Dockerfile
        build-args: |
          D_OS=${{ matrix.os }}${{ matrix.version }}
          D_OFED_OS_VERSION=${{ env.LATEST_DOCA_VERSION }}
          D_KERNEL_VER=${{ env.LATEST_KERNEL_VERSION }}
          D_BASE_IMAGE=${{ env.BASE_IMAGE }}
        tags: ${{ env.NVCR_DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
        push: false  # TODO: change to true once build successful and satisfied with the matrix
