name: Build precompiled DOCA for latest Kernels
# TODO: ask ivan (maybe also alex) about what automation to maybe add for promotion from nvstaging to NGC
# OFED releases: ask vlad.l who knows about it - perhaps mohamed.(!t)

on:
  workflow_dispatch:  # TODO: configure upstream trigger in DOCA CI releases
    inputs:
      latest_doca_version:  # e.g. '23.10-0.5.5.0'
        description: Version of DOCA built in upstream job
        required: true
        default: '24.07-0.6.1.0'  # TODO: remove default after testing

env:
  NVCR_DOCKER_REGISTRY: nvcr.io/nvstaging/mellanox  # TODO: verify if to publish to NGC or directly to nvstaging
  DOCKER_IMAGE_NAME: doca-driver

jobs:
  precompile_and_publish_doca_for_ubuntu:
    runs-on: ubuntu-latest
    env:
      LATEST_DOCA_VERSION: ${{ inputs.latest_doca_version }}  # TODO: acquire latest version from DOCA release pipeline (or equivalent source)
    strategy:
      matrix:
        flavor:
        - generic
        - aws
        - azure
        - oracle
        - nvidia
        version:
        - '24.04'
        - '22.04'
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.NVCR_DOCKER_REGISTRY }}
        username: ${{ secrets.NVCR_USERNAME }}
        password: ${{ secrets.NVCR_TOKEN }}
    - name: Fetch latest Kernel version
      run: |
        echo LATEST_KERNEL_VERSION=$(docker run --rm ubuntu:${{ matrix.version }} bash -c "
          apt-get update > /dev/null
          apt-cache search --names-only linux-image | grep -Eo 'linux-image-[0-9.-]+${{ matrix.flavor }}' | sed -E 's/linux-image-//g' | sort -V | tail -n 1"
        ) | tee -a $GITHUB_ENV
    - name: Define docker tag
      run: |
        echo DOCKER_TAG=$LATEST_DOCA_VERSION-$LATEST_KERNEL_VERSION-ubuntu${{ matrix.version }} | tee -a $GITHUB_ENV
    - name: Check if published precompiled DOCA for kernel version
      id: check-if-published-precompiled-for-kernel
      run: |
        if skopeo list-tags docker://$NVCR_DOCKER_REGISTRY/$DOCKER_IMAGE_NAME | jq '.Tags[]' -r | grep $LATEST_DOCA_VERSION | grep ${{ matrix.flavor }}-ubuntu${{ matrix.version }}
        then
          echo NEW_BUILD_REQUIRED=false >> $GITHUB_ENV
        else
          echo NEW_BUILD_REQUIRED=true  >> $GITHUB_ENV
        fi
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/setup-qemu-action@v3
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/setup-buildx-action@v3
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64,linux/arm64
        file: Ubuntu_Dockerfile
        build-args: |
          D_OS=ubuntu${{ matrix.version }}
          D_OFED_VERSION=${{ env.LATEST_DOCA_VERSION }}
          D_KERNEL_VER=${{ env.LATEST_KERNEL_VERSION }}
          D_BASE_IMAGE=ubuntu:${{ matrix.version }}
        tags: ${{ env.NVCR_DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
        push: false  # TODO: change to true once build successful and satisfied with the matrix

  precompile_and_publish_doca_for_redhat_and_coreos:
    if: false
    runs-on: ubuntu-latest
    env:
      RH_MAJOR_VERSION_FOR_RHCOS: 9  # TODO: define what this should be (for rhcos), and how its value should be *manually* updated (perhaps highest from `matrix.version` list?)...
      LATEST_DOCA_VERSION: ${{ inputs.latest_doca_version }}
      RH_USERNAME: mzeevi@nvidia.com  # TODO: RH double check if there is a possibility for a service account instead of user account
    strategy:
      matrix:
        os:
        - rhel
        version:
        - '9.4'
        - '9.3'
        - '9.2'
        - '8.10'
        - '8.9'
        - '8.8'
        include:
        - os: rhcos
          version: '4.16'
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: registry.redhat.io  # required for build
        username: ${{ env.RH_USERNAME }}
        password: ${{ secrets.RH_PASSWORD }}  # TODO: add secret in github
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.NVCR_DOCKER_REGISTRY }}
        username: ${{ secrets.NVCR_USERNAME }}  # TODO: add secret in github
        password: ${{ secrets.NVCR_TOKEN }}     # TODO: add secret in github
    - name: Fetch latest Kernel version
      run: |
        [[ "${{ matrix.os }}" == "rhcos" ]] && major_version=$RH_MAJOR_VERSION_FOR_RHCOS
        echo LATEST_KERNEL_VERSION=$(docker run --rm redhat/ubi$major_version:latest yum repoquery | grep kernel-headers | cut -d ':' -f 2) | tee $GITHUB_ENV
    - name: Define docker tag
      run: |
        echo DOCKER_TAG=$LATEST_DOCA_VERSION-$LATEST_KERNEL_VERSION-${{ matrix.os }}${{ matrix.version }} >> $GITHUB_ENV
    - name: Check if published precompiled DOCA for kernel version
      id: check-if-published-precompiled-for-kernel
      run: |
        if skopeo list-tags docker://$NVCR_DOCKER_REGISTRY/$DOCKER_IMAGE_NAME | jq '.Tags[]' -r | grep $DOCKER_TAG
        then
          echo NEW_BUILD_REQUIRED=false >> $GITHUB_ENV
        else
          echo NEW_BUILD_REQUIRED=true  >> $GITHUB_ENV
        fi
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/setup-qemu-action@v3
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/setup-buildx-action@v3
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      name: Determine base image
      run: |
        if [[ "${{ matrix.os }}" == "rhel" ]]
        then
          echo BASE_IMAGE=$(TBD) | tee -a $GITHUB_ENV  # TODO: find dynamic command to lookup image
        elif [[ "${{ matrix.os }}" == "rhcos" ]]
        then
          # podman login registry.redhat.io --username=${RH_USERNAME} --password=${RH_PASSWORD}  # TODO: see if required
          echo BASE_IMAGE=$(oc adm release info ${{ matrix.version }}.0 --image-for=driver-toolkit) | tee -a $GITHUB_ENV
        fi
    - if: ${{ env.NEW_BUILD_REQUIRED }}
      uses: docker/build-push-action@v4
      with:
        platforms: ${{ matrix.os == 'rhel' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
        file: RHEL_Dockerfile
        build-args: |
          D_OS=${{ matrix.os }}${{ matrix.version }}
          D_OFED_OS_VERSION=${{ env.LATEST_DOCA_VERSION }}
          D_KERNEL_VER=${{ env.LATEST_KERNEL_VERSION }}
          D_BASE_IMAGE=${{ env.BASE_IMAGE }}
        tags: ${{ env.NVCR_DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}
        push: false  # TODO: change to true once build successful and satisfied with the matrix
